routes:
  /rss/episode/:
    template: rss
    content_type: text/xml
collections:
  /:
    permalink: /{slug}/
    template: index
    filter: tag:-blog

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
